### ISSUE TITLE
Add these features plz 

### ISSUE THREAD

**Issue by Itzmepapa21** [kaif-00z/AutoAnimeBot#6]
1st. Add episode and season in format

2nd. Add forwarding to main channel with link of ongoing post uploaded by the bot

3rd. add Hdrip {Subsplease 1080p with metadata editing only ask rengoku he will provide ffmpeg}

4th. Use mongodb as it's best available {redis storage is too less}

5th. Use quotes to make format even better

6th.Show encoding progress with time left and percentage at ongoing channel to make viewer engaged
** thanks for reading sur**

**Comment by kaif-00z** [comment]
Almost Every Point Is Irrelevant Except First One Which Is Already Added
