### ISSUE TITLE
Force Sub 

### ISSUE THREAD

**Issue by itzmadara** [kaif-00z/AutoAnimeBot#8]
Bro Can U add Force Sub In [Button]
![Screenshot_20240521_072219](https://github.com/kaif-00z/AutoAnimeBot/assets/141416632/8091776f-48c1-48ab-87e9-f118c66c7f94)
Expect This Bcz Its not Looking Good 😅
And Also Can u add 2fsub buttons

**Comment by kaif-00z** [comment]
> Bro Can U add Force Sub In [Button] ![Screenshot_20240521_072219](https://private-user-images.githubusercontent.com/141416632/332250432-8091776f-48c1-48ab-87e9-f118c66c7f94.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzIwMzYsIm5iZiI6MTcxNjI3MTczNiwicGF0aCI6Ii8xNDE0MTY2MzIvMzMyMjUwNDMyLTgwOTE3NzZmLTQ4YzEtNDhhYi04N2U5LWYxMThjNjZjN2Y5NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwNjA4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2M1MTE5MWZmNGI0NmU2NGYzOWIzYTA2ZDkyNDU4MGFjMDZmY2VlNWNlYTA5MmYwY2QzZGVlZThhYmVmOTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mo5MzPCrI45ov93fxN4-C85UnNT_9LpLqU1pR_8rRKw) Expect This Bcz Its not Looking Good 😅 And Also Can u add 2fsub buttons

yeah will look into it

**Comment by kaif-00z** [comment]
> Bro Can U add Force Sub In [Button] ![Screenshot_20240521_072219](https://private-user-images.githubusercontent.com/141416632/332250432-8091776f-48c1-48ab-87e9-f118c66c7f94.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzMyNzYsIm5iZiI6MTcxNjI3Mjk3NiwicGF0aCI6Ii8xNDE0MTY2MzIvMzMyMjUwNDMyLTgwOTE3NzZmLTQ4YzEtNDhhYi04N2U5LWYxMThjNjZjN2Y5NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwNjI5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmFiNTQ2N2IwNjJlNjQ2NTg2MzU2MWNiZjU1ZDdlMDBkNzI0Mjk4YWNiYmMzYjFmNzE5NjQ5NTlmZGFlZTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GrxEqggQ2KZNShMbhONm7h2CJoxOnYAyQtf-aanZJCI) Expect This Bcz Its not Looking Good 😅 And Also Can u add 2fsub buttons

to help community user will not add 2 fsub coz it will annoy the users

**Comment by itzmadara** [comment]
> > Bro Can U add Force Sub In [Button] ![Screenshot_20240521_072219](https://private-user-images.githubusercontent.com/141416632/332250432-8091776f-48c1-48ab-87e9-f118c66c7f94.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzMyNzYsIm5iZiI6MTcxNjI3Mjk3NiwicGF0aCI6Ii8xNDE0MTY2MzIvMzMyMjUwNDMyLTgwOTE3NzZmLTQ4YzEtNDhhYi04N2U5LWYxMThjNjZjN2Y5NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwNjI5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmFiNTQ2N2IwNjJlNjQ2NTg2MzU2MWNiZjU1ZDdlMDBkNzI0Mjk4YWNiYmMzYjFmNzE5NjQ5NTlmZGFlZTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GrxEqggQ2KZNShMbhONm7h2CJoxOnYAyQtf-aanZJCI) Expect This Bcz Its not Looking Good 😅 And Also Can u add 2fsub buttons
> 
> to help community user will not add 2 fsub coz it will annoy the users

But Sir u don't thik so Like this Force sub are not looking Good if u can attach with buttons force sub 😊
