### ISSUE TITLE
Rss Feed 

### ISSUE THREAD

**Issue by itzmadara** [kaif-00z/AutoAnimeBot#9]
Sir Can U add Manuall Rss Feed.Its Help In Dual Audio, Multiple Audio And Eng Dub Also 🙂

If Can't then Thanku For Hard Working On Auto Anime Bot. This Repo Is Wonderful At this time for free 👍

**Comment by kaif-00z** [comment]
> Sir Can U add Manuall Rss Feed.Its Help In Dual Audio, Multiple Audio And Eng Dub Also 🙂
> 
> If Can't then Thanku For Hard Working On Auto Anime Bot. This Repo Is Wonderful At this time for free 👍

You Can Use Any RSS feed but u have to know what u are doing

**Comment by itzmadara** [comment]
> > Sir Can U add Manuall Rss Feed.Its Help In Dual Audio, Multiple Audio And Eng Dub Also 🙂
> > If Can't then Thanku For Hard Working On Auto Anime Bot. This Repo Is Wonderful At this time for free 👍
> 
> You Can Use Any RSS feed but u have to know what u are doing

Really Sir I tried But I facing Some issues 😁

**Comment by kaif-00z** [comment]
> > > Sir Can U add Manuall Rss Feed.Its Help In Dual Audio, Multiple Audio And Eng Dub Also 🙂
> > > If Can't then Thanku For Hard Working On Auto Anime Bot. This Repo Is Wonderful At this time for free 👍
> > 
> > 
> > You Can Use Any RSS feed but u have to know what u are doing
> 
> Really Sir I tried But I facing Some issues 😁

Then You don't know how to do it
